# Generated by Django 2.0.3 on 2018-03-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('jenis_daftar', models.CharField(choices=[('Regular', 'Regular'), ('Transfer', 'Transfer')], max_length=10)),
                ('no_telepon', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('kode_progdi', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nama_progdi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='progdi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.ProgramStudi'),
        ),
    ]
