# Generated by Django 2.0.3 on 2018-04-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_dosen_kelas_matakuliah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('kode_kurikulum', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nama_kurikulum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliahKurikulum',
            fields=[
                ('id_kurikulum', models.AutoField(primary_key=True, serialize=False)),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Kurikulum')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.MataKuliah')),
            ],
        ),
        migrations.CreateModel(
            name='TahunAkademik',
            fields=[
                ('id_tahun_akademik', models.AutoField(primary_key=True, serialize=False)),
                ('tahun', models.CharField(max_length=11)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=6)),
            ],
        ),
    ]
