# Generated by Django 2.0.3 on 2018-04-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_kurikulum_matakuliahkurikulum_tahunakademik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='mata_kuliah',
            new_name='Mata_kuliah',
        ),
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='id_kurikulum',
            new_name='id',
        ),
    ]
