# Generated by Django 2.0.3 on 2018-04-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20180403_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='Mata_kuliah',
            new_name='mata_kuliah',
        ),
    ]
