# Generated by Django 2.0.3 on 2018-04-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20180403_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='id',
            new_name='id_matakuliahkurikulum',
        ),
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='kurikulum',
            new_name='kurikulum_matakuliah',
        ),
    ]
