# Generated by Django 2.0.3 on 2018-04-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20180403_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='id_matakuliahkurikulum',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='kurikulum_matakuliah',
            new_name='kurikulum',
        ),
    ]
