# Generated by Django 2.0.3 on 2018-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20180403_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliahkurikulum',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
