# Generated by Django 2.0.3 on 2018-04-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20180403_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliahkurikulum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
