# Generated by Django 2.0.3 on 2018-05-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_angka', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('nilai_huruf', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('krs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaksi.Krs')),
            ],
        ),
    ]
