# Generated by Django 2.0.3 on 2018-05-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_nilai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilai',
            old_name='nilai_angka',
            new_name='angka',
        ),
        migrations.RenameField(
            model_name='nilai',
            old_name='nilai_huruf',
            new_name='huruf',
        ),
    ]
