# Generated by Django 2.0.3 on 2018-05-08 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_auto_20180508_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='tgl_input',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
